name: Tests Workflow

on: [push]

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare to tests
        run: npm i
      - name: Tests
        run: npm run test
